"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
F1 = HERE / "field_f1" / "results"
AA = HERE / "annotator_agreement" / "results"
CP = HERE / "cost_per_paper" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    f1 = _read(F1 / "results.json")
    aa = _read(AA / "results.json")
    cp = _read(CP / "results.json")
    f1_md = _md(F1 / "results.md")
    aa_md = _md(AA / "results.md")
    cp_md = _md(CP / "results.md")
    f1_lines = f1_md.splitlines()
    f1_start = next(i for i, line in enumerate(f1_lines) if line.startswith("| field |"))
    f1_table = "\n".join(f1_lines[f1_start:])
    aa_table = "\n".join(line for line in aa_md.splitlines() if line.startswith("|"))
    cp_table = "\n".join(line for line in cp_md.splitlines() if line.startswith("|"))
    cost = "\n".join(
        [
            f"- Mean input tokens / paper: {cp['models'][0]['mean_input_tokens_per_paper']:.1f}",
            f"- Cheapest / paper: {cp['decision']}",
            f"- Local tokenize time: {cp['local_render_and_tokenize_seconds'] * 1000:.2f} ms "
            f"({cp['local_ms_per_paper']:.2f} ms/paper)",
            "- API RTT: unmeasured",
            "- Human annotation minutes per paper: unmeasured",
        ]
    )
    filled = (
        template.replace("{{F1_N}}", str(f1["n_papers"]))
        .replace("{{F1_MEDIAN}}", f"{f1['median_field_f1']:.3f}")
        .replace("{{F1_DECISION}}", str(f1["decision"]))
        .replace("{{F1_TABLE}}", f1_table)
        .replace("{{AA_N}}", str(aa["n_papers"]))
        .replace("{{AA_VALUE}}", f"{aa['value_agreement']:.3f}")
        .replace("{{AA_DECISION}}", str(aa["decision"]))
        .replace("{{AA_TABLE}}", aa_table)
        .replace("{{CP_N}}", str(cp["n_papers"]))
        .replace("{{CP_TABLE}}", cp_table)
        .replace("{{CP_DECISION}}", str(cp["decision"]))
        .replace("{{CP_LOCAL_MS}}", f"{cp['local_render_and_tokenize_seconds'] * 1000:.2f}")
        .replace("{{COST_MODEL}}", cost)
    )
    return filled


def render_eval() -> str:
    f1 = _md(F1 / "results.md")
    aa = _md(AA / "results.md")
    cp = _md(CP / "results.md")
    f1_json = _read(F1 / "results.json")
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. "
        "Live PMC OA hold-out numbers do not exist yet. "
        "Median field F1 decides whether a completeness leaderboard is defensible.\n\n"
        f"Median field F1: **{f1_json['median_field_f1']:.3f}**. "
        f"Leaderboard defensible: **{'yes' if f1_json['leaderboard_defensible'] else 'no'}**.\n\n"
        f"{f1}\n\n{aa}\n\n{cp}\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    path = ROOT / "README.md"
    if not path.exists():
        return
    f1 = _read(F1 / "results.json")
    aa = _read(AA / "results.json")
    cp = _read(CP / "results.json")
    body = (
        "| Measurement | Result | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Median field F1 | {f1['median_field_f1']:.3f} | {f1['n_papers']} | "
        f"Floor {f1['median_floor']:.2f} |\n"
        f"| Annotator value agreement | {aa['value_agreement']:.3f} | {aa['n_papers']} | "
        "Upper bound on extraction accuracy |\n"
        f"| Cheapest USD/paper (input+assumed output) | "
        f"{min(m['usd_per_paper'] for m in cp['models']):.6f} | {cp['n_papers']} | "
        "tiktoken + committed prices |\n"
        "| Live PMC OA completeness leaderboard | Phase 3 | — | Not pulled |\n\n"
        f"{f1['decision']}"
    )
    path.write_text(
        _replace_block(
            path.read_text(encoding="utf-8"),
            "<!-- EVAL_TABLE_BEGIN -->",
            "<!-- EVAL_TABLE_END -->",
            body,
        ),
        encoding="utf-8",
    )


def main() -> None:
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(render_memo(), encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    patch_readme()
    print("wrote docs/phase-0/research-memo.md, docs/EVALUATION.md, README results block")


if __name__ == "__main__":
    main()
